<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Discord.Net.Commands\Discord.Net.Commands.csproj" />
    <ProjectReference Include="..\Discord.Net.Interactions\Discord.Net.Interactions.csproj" />
  </ItemGroup>

</Project>
